<?php
$config['full_tag_open'] = '<ul class="ch-pagination">';
$config['full_tag_close'] = '</ul>';
$config['cur_tag_open'] = '<li class=active>';
$config['cur_tag_close'] = '</li>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
$config['next_link'] = '<i class="icn icon-chevron-right"></i>';
$config['prev_link'] = '<i class="icn icon-chevron-left"></i>';
$config['last_link'] = '<i class="icn icon-fast-forward"></i>';
$config['first_link'] = '<i class="icn icon-fast-backward"></i>';
$config['next_tag_open']= '<li title="selanjutnya">';
$config['next_tag_close']= '</li>';
$config['prev_tag_open']= '<li title="sebelumnya">';
$config['prev_tag_close']= '</li>';
$config['first_tag_open']		= '<li title="awal">';
$config['first_tag_close']	= '</li>';
$config['last_tag_open']		= '<li title="terakhir">';
$config['last_tag_close']		= '</li>';
$config['showing_text']       = 'menampilkan';
$config['to_text']       = 'sampai';
$config['of_text']       = 'dari';
